name: Linter check

on:
  workflow_dispatch:
  pull_request:

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: CSharpier Linter
        uses: guibranco/github-csharpier-linter-action@7cecc055044a24d226b8b17fc67c864e64da945f # v1.0.24
